# Generated by Django 2.2.4 on 2019-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='amount',
            field=models.FloatField(default=1),
        ),
    ]
