# Generated by Django 2.2.4 on 2019-09-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodman', '0004_auto_20190904_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='dish_persons',
            new_name='persons',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='dish_recipe',
            new_name='recipe',
        ),
    ]
